MODEL:
  TYPE: "LateFusionTransformer"
  DUAL_HEAD: True
  NUM_CLASSES: 20
  block_number: 11
DATASET:
  TYPE: "SemanticKITTISCN"
  TRAIN: ("train",)
  VAL: ("val",)
  TEST: ("test",)
  SemanticKITTISCN:
    preprocess_dir: "/home/user/SemanticKitti/semantic_kitti_preprocess/preprocess"
    semantic_kitti_dir: "/home/user/SemanticKitti"
DATALOADER:
  NUM_WORKERS: 4
OPTIMIZER:
  TYPE: "Adam"
  BASE_LR: 0.001
SCHEDULER:
  TYPE: "MultiStepLR"
  MultiStepLR:
    gamma: 0.1
    milestones: (80000, 90000)
  MAX_ITERATION: 100000
TRAIN:
  BATCH_SIZE: 1
  SUMMARY_PERIOD: 50
  CHECKPOINT_PERIOD: 5000
  # CLASS_WEIGHTS: [1.89090012, 2.0585112, 3.1970535, 3.1111633, 1., 2.93751704, 1.92053733,
  #                 1.47886874, 1.04654198, 1.78266561]
VAL:
  BATCH_SIZE: 2
  PERIOD: 5000
#OUTPUT_DIR: "path/to/output/directory/@"  #  @ will be replaced with config path, e.g. nuscenes/usa_singapore/FusionTransformer
